name: incloud


on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev 
           
        

      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up ProjectDiscovery tools
        if: steps.cache-go.outputs.cache-hit != 'true'
        env:
          GO111MODULE: on
        run: |
          go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
          git clone https://github.com/projectdiscovery/nuclei-templates.git
          cd /root/nuclei-templates && git clone https://github.com/ExpLangcn/NucleiTP.git
          cd /root/nuclei-templates && git clone https://github.com/ayadim/Nuclei-bug-hunter.git
          
        shell: bash
        
      - name: Running nuclei scaning
        run: |
          nuclei -l input/target.txt -t /root/nuclei-templates -o output/vuln.txt | tee output/vuln.txt
        shell: bash

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add output/vuln.txt
          
        shell: bash

      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add output/vuln.txt
